# Generated by Django 4.2.30 on 2026-09-23 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('ballot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(db_column='candidate_id', on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='elections.candidate')),
                ('election', models.ForeignKey(db_column='election_id', on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='elections.election')),
            ],
            options={
                'verbose_name': 'Ballot',
                'verbose_name_plural': 'Ballots',
            },
        ),
    ]
