# Generated by Django 4.2.30 on 2026-09-23 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uuid_token', models.UUIDField(default=uuid.uuid4, help_text='Single-use session-bound token (FR-V-03 / FR-S-01).', unique=True)),
                ('expiry_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('voter', models.ForeignKey(db_column='voter_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='voters.voter')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
