# Generated by Django 4.2.30 on 2026-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_election_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', help_text='Open/close lifecycle state (DRAFT/OPEN/CLOSED). Use open_voting()/close_voting() to transition rather than setting this field directly, so the only-forward-one-step rule (FR-A-03) is enforced.', max_length=10),
        ),
    ]
