# Generated by Django 4.2.30 on 2026-09-23 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id_hash', models.CharField(help_text='Hashed National ID -- the raw National ID is never stored.', max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp_hash', models.CharField(blank=True, help_text='Hashed OTP secret. Populated by the MFA pipeline (Sprint 2, FR-V-03).', max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True, help_text='Set under FR-V-00 at registration time.')),
                ('has_voted', models.BooleanField(default=False, help_text='Checked at authentication under FR-V-02.')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
            },
        ),
    ]
