# Generated by Django 4.2.30 on 2026-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='national_id_hash',
            field=models.CharField(help_text="Hashed National ID -- the raw National ID is never stored. unique=True enforces FR-V-00's uniqueness requirement at the database level (Sprint 3 correction): the application-layer check in VoterRegistrationForm.clean_national_id alone can't stop two concurrent registration requests for the same National ID both passing validation before either commits -- the DB constraint is what actually closes that race.", max_length=255, unique=True),
        ),
    ]
