# Generated by Django 4.2.30 on 2026-09-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=100)),
                ('ballot_hash', models.CharField(blank=True, help_text='SHA-256 hex digest, generated under FR-V-07 (Sprint 3).', max_length=64)),
                ('previous_hash', models.CharField(blank=True, help_text='Chains entries so the sequence itself is verifiable.', max_length=64)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
            },
        ),
    ]
